#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.

# Update package lists and install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy


# Define new HAProxy configuration
server_config=\
"
frontend my_frontend
    bind *:80
    mode http
    default_backend my_backend

backend my_backend
    balance roundrobin
    server 284492-web-01 100.25.102.62:80 check
    server 284492-web-02 52.87.24.245:80 check
"

# Append the new configuration to HAProxy configuration